@startuml Container 
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"
!include $ICONURL/common.puml

!include $ICONURL/common.puml
!include $ICONURL/devicons/mysql.puml
!include $ICONURL/font-awesome/server.puml
!include $ICONURL/font-awesome-5/database.puml
!include $ICONURL/devicons2/spring_original.puml
!include $ICONURL/devicons2/react_original.puml
!include $ICONURL/devicons2/okta.puml
!include $ICONURL/devicons2/google.puml

Person(consolidator, "Consolidator", "User who registers the church visitors")

System_Boundary(consolidation_system, "Consolidation System") {
    System(consolidation_app, "Consolidation App", "Application that helps in registering church visitors", , $sprite="react_original")

    Container(consolidation_api, "Consolidation API", "Spring Boot", "Application that helps in registering church visitors", $sprite="spring_original")
    ContainerDb(mysql_db, "ConsolidationDb", "MySQL", "Database that stores the church visitors data", $sprite="mysql")

    System_Ext(auth_system, "Auth API", "Manages authorization and authentication of users", $sprite="okta")
    System_Ext(zipcode_api, "ZipCodeAPI", "External system responsible for registering and locating ZIP codes", $sprite="google")


    Rel(consolidation_app, consolidation_api, "Sends a POST HTTP request")
    Rel(consolidation_api, auth_system, "http client")
    Rel(consolidation_api, zipcode_api, "http client")
    Rel(consolidation_api, mysql_db, "Persists")
}

Rel(consolidator, consolidation_app, "Uses")

LAYOUT_WITH_LEGEND()

@enduml